site_name: Streval
repo_url: "https://github.com/ruankie/streval"
repo_name: "ruankie/streval"

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Examples: examples.md
  - Reference: reference.md

theme:
  name: material
  logo: img/logo_sq_white_no_bg.png
  favicon: img/favicon.ico
  features:
    - tabs
    - navigation.expand
    - navigation.sections

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css